export const ActionTypes = {
    FETCH_USER_DETAILS:"FETCH_USER_DETAILS",
    SET_LOGIN_DETAILS:"SET_LOGIN_DETAILS",
    SET_OTP_BOX_OPEN:"SET_OTP_BOX_OPEN",
    RESEND_OTP : "RESEND_OTP",
    LOGIN_SUCCESS : "LOGIN SUCCESS",
    SET_TOKEN : "SET_TOKEN",
    SET_TOKEN_EXPIRETIME : "SET TOKEN EXPIRE TIME",
    FETCH_LEDGER_DETAILS : "FETCH_LEDGER_DETAILS"
}